HDSLabs/co-care-exchange-client

src/app/auth/password-forgot/password-forgot.component.ts, src/app/auth/password-reset/password-reset.component.ts, src/app/aws-cognito/cognito/password.ts, src/app/constants/routes.ts, src/app/services/cce/authentication.service.ts
- added routing 
- added reset complete service
- tied into forget and reset password views
=> feat(auth): add password reset

src/app/interceptors/jwt.interceptor.ts, src/app/services/cce/authentication.service.ts
- added X-COG-ID key to header with the user idToken
- updated authservice to expose idToken
=> feat(http): add idToken to header

.prettierignore, .prettierrc, src/app/app.routing.ts, src/app/auth/routes/auth-routing.module.ts, src/app/dashboard/routes/dashboard-routing.module.ts, src/app/information/information-routing.module.ts, src/app/registration/routes/registration-routing.module.ts
- moved signin routing
- moved dashboard routing
- adder prettier config
=> refactor(app): move to module routing

src/app/dashboard/components/dashboard.component.html, src/app/dashboard/components/dashboard.component.scss, src/app/dashboard/components/dashboard.component.ts, src/app/dashboard/components/models/agreement.ts, src/app/dashboard/components/models/dasboard.ts, src/app/dashboard/components/status-dialog/status-dialog.component.html, src/app/dashboard/components/status-dialog/status-dialog.component.ts, src/app/services/cce/dashboard.service.ts, src/app/shared/shared.module.ts, src/app/shared/site-footer/site-footer.component.html, src/app/shared/site-footer/site-footer.component.ts
This is to setup the handoff to Josh
=> Dashboard connectdata

buildspec.yml
- updated buildspec to build with more memory
=> build(cce): fix npm build

src/app/auth/components/sign-in/sign-in.component.ts
- fixed array processing of orgs
=> fix(signin): only show individuals once

src/app/pantry-locator/pantry-locator.component.ts, src/app/pantry-locator/pantry-locator.module.ts, src/app/prompts/prompt.module.ts, src/app/prompts/prompts-organization/prompts-organization-summary/prompts-organization-summary.component.ts
- added to prompts module
- added the missing properties used in html to the components
=> fix(prompts): declare components in module, add missing properties

src/app/prompts/prompts-routing.module.ts
- added prompt route to org info component
=> fix(prompts): add route to org prompt (temp fix)

src/app/auth/components/sign-in/sign-in.component.ts, src/app/core/services/organization.service.ts, src/app/core/services/user.service.ts, src/app/graphql/graphql.module.ts, src/app/graphql/models/create-user-input.model.ts, src/app/information/individual/individual.component.ts, src/app/information/information/information.component.html, src/app/information/information/information.component.ts, src/app/information/models/info-create.model.ts, src/app/information/organization/organization.component.ts, src/app/interceptors/jwt.interceptor.ts, src/environments/commonEnv.ts
- update info compoments to pass data down, events up
- fixed service call for getUser
- updated endpoint/apikey
=> feat(register): build out framework for user org registration

src/app/auth/components/sign-in/sign-in.component.ts, src/app/information/individual/individual.component.html, src/app/information/individual/individual.component.ts, src/app/information/information/information.component.html, src/app/information/organization/organization.component.html, src/app/information/organization/organization.component.ts
- made email, org readly
- broke out cityState to separate city, state, and postalCode inputs
- removed radio button individual/organization selection
=> feat(information): update forms to better match backend data model

src/app/graphql/models/create-user-input.model.ts, src/app/information/individual/individual.component.html, src/app/information/individual/individual.component.ts, src/app/information/information/information.component.html, src/app/information/information/information.component.ts, src/app/information/organization/organization.component.ts
- added save user GQL call
- happy path and error handling
- misc fixes to forms
=> feat(information): added save profile logic off of info view

buildspec.yml, src/app/dashboard/components/status-dialog/status-dialog.component.html
- removed .data
- updated buildspec to only delete on build failure (I hope)
=> fix(status-dlalog): remove invalid property

src/app/core/services/user.service.ts, src/app/information/individual/individual.component.ts, src/app/information/information/information.component.html, src/app/information/information/information.component.ts, src/app/information/organization/organization.component.ts
- renamed submit to infoSubmit to avoid collision
- fixed response handling/parsing of createUser
=> fix(info): fix submit and response handling

src/app/app.module.ts, src/app/services/cce/answer.service.ts, src/app/services/cce/dashboard.service.ts, src/app/services/cce/prompt.service.ts
- provided interceptor in appmodule
- removed http header option sets in network calls
=> refactor(network): use http interceptor for setting x-api-key

src/app/core/services/user.service.ts
- assigned profile on save
- added phoneNumber and other fields
=> fix(user-service): fix current user profile

src/app/prompts/prompts-organization/prompts-organization.component.ts, src/app/services/cce/prompt.service.ts
=> adding size to prompt service

src/environments/commonEnv.ts
- changed to api.cocareexchange.org
=> build(config): update api endpoint

src/app/aws-cognito/cognito/signin.ts, src/app/services/cce/authentication.service.ts
- added clientMetadata to signin parameters
DEV NOTE: to be used in the future to allow cognito to perform the user-org auth
=> fix(auth): add organization to clientMetadata

src/app/core/services/organization.service.ts, src/app/core/services/user.service.ts, src/app/graphql/models/save-user-input.model.ts, src/app/information/individual/individual.component.ts, src/app/information/information/information.component.ts, src/app/information/models/info-create.model.ts, src/app/information/organization/organization.component.html, src/app/information/organization/organization.component.ts
saveUser Profile mutation integration
WIP: still need to pull in profile detail into form if existing user. I will follow up with that shortly after merge.
=> Issue/64 saveUser mutation

src/app/prompts/prompts/prompts.component.html, src/app/prompts/prompts/prompts.component.ts
only send 0 amounts to service
=> Prompt zeroamounts

src/app/core/services/cce/prompt.service.ts, src/app/prompts/prompts/prompts.component.html, src/app/prompts/prompts/prompts.component.scss
this will allow amount to be entered manually for prompts
It will also send only single size to backend for posting
=> Prompts enter amounts

src/app/app.module.ts, src/app/app.routing.ts, src/app/aws-cognito/cognito/signin.ts, src/app/aws-cognito/config/awsconfig.ts, src/app/core/services/cce/authentication.service.ts, src/app/core/services/cce/dashboard.service.ts, src/app/core/services/user.service.ts, src/app/dashboard/routes/dashboard-routing.module.ts
- added refresh support for dashboard
=> feat(auth): add browser refresh session (partial)

src/app/dashboard/components/dashboard.component.ts
=> debug dashboard needs and shares

src/app/auth/components/sign-in/sign-in.component.html, src/app/auth/components/sign-in/sign-in.component.scss, src/app/prompts/prompts/prompts.component.html, src/app/prompts/prompts/prompts.component.scss, src/app/registration/components/register/register.component.html, src/app/registration/components/register/register.component.scss, src/styles/components.scss
- Fix header text for login
- move login down to below text entry
- reduce padding
- center text on prompt questions
=> Fixes for bugs: 116 and 101

src/app/app.routing.ts, src/app/auth/AuthModule.ts, src/app/auth/components/sign-in/sign-in.component.ts, src/app/core/resolvers/user.resolver.spec.ts, src/app/core/resolvers/user.resolver.ts, src/app/dashboard/components/dashboard.component.ts, src/app/dashboard/routes/dashboard-routing.module.ts
- made the GQL polling timer hot/multicast
- added user resolver shell (partial)
=> fix(dashboard): fix redundant service calls

src/app/prompts/prompts/prompts.component.html, src/app/prompts/prompts/prompts.component.scss
just adding padding and sizing for prompt summary
=> Prompt summaryspacingfix

src/app/auth/components/sign-in/sign-in.component.ts, src/app/core/services/cce/authentication.service.ts, src/app/core/services/user.service.ts, src/app/interceptors/error.interceptor.ts, src/app/shared/site-header/site-header.component.ts
- added username prefix to local storage userProfile
- updated logout to be via user service
- added initial signin login
=> fix(auth): update local storage for user profile

src/app/dashboard/components/dashboard.component.html, src/app/dashboard/components/dashboard.component.ts
- added progress indicators on initial load
- fixed component display logic
=> fix(dashboard): fix load display delay, add progress indicators

src/app/dashboard/components/dashboard.component.html, src/app/dashboard/components/dashboard.component.ts
- refactored to single view subscription per share and need
- better use of templates and angular fun stuff
=> fix(dashboard): refactored the subscriptions

src/app/dashboard/components/dashboard.component.ts
- fixed to get userprofile from userservice
=> fix(dashboard): get valid user profile

src/app/dashboard/components/dashboard.component.ts
- fixed to get userprofile from userservice for another code path
=> fix(dashboard): get valid user profile--again

src/app/auth/components/sign-in/sign-in.component.html, src/app/auth/components/welcome-page/welcome.component.scss, src/app/dashboard/components/dashboard.component.scss, src/app/dashboard/components/dashboard.component.ts
=> Dashboard wrapfix

README.md, angular.json, src/app/aws-cognito/config/awsconfig.ts, src/app/aws-cognito/config/individuals.ts, src/app/aws-cognito/config/organizations.ts, src/environments/awsEnv.prod.ts, src/environments/awsEnv.qa.ts, src/environments/commonEnv.ts, src/environments/environment.prod.ts, src/environments/environment.qa.ts, src/environments/environment.ts
- added qa config
- updated prod and qa service endpoints
=> config(app): add qa and prod configs

src/environments/environment.prod.ts, src/environments/environment.qa.ts, src/environments/environment.ts
removed ? from api graphql endpoing URL; set dev api URL on src/environments/environment.ts
=> dash config updates

angular.json, src/app/core/services/cce/authentication.service.ts, src/environments/awsEnv.qa.ts, src/environments/environment.dev.ts
- changed qa/dev CUP app id
- removed some user profile contraints on the auth service
- added dev config (faster local dev)
=> fix(app): updated CUP client app id

src/app/core/services/cce/dashboard.service.ts, src/app/dashboard/components/agreement-detail/agreement-detail.component.ts, src/app/dashboard/components/dashboard.component.ts, src/environments/environment.prod.ts, src/environments/environment.qa.ts, src/environments/environment.ts
removed ? from api graphql endpoing URL; set dev api URL on src/environments/environment.ts
=> Better update mutation logging, sample push to master for scott

src/app/auth/components/password-reset/password-reset.component.ts, src/app/auth/components/registration/components/register/register.component.html, src/app/auth/components/registration/components/register/register.component.ts, src/app/auth/components/sign-in/sign-in.component.html, src/app/auth/components/sign-in/sign-in.component.ts, src/app/auth/routes/auth-routing.module.ts, src/app/aws-cognito/cognito/register.ts, src/app/core/constants/routes.ts, src/app/core/services/cce/authentication.service.ts, src/app/core/services/cce/dashboard.service.ts, src/app/models/cce/basic-registration.model.ts, src/app/pantry-locator/pantry-locator.component.ts, src/app/prompts/prompts/prompts.component.ts, src/environments/environment.ts
this also cleans up a bit of the login page and routing
=> signup add orgselect

src/app/auth/components/password-reset/password-reset.component.ts, src/app/auth/components/registration/components/register/register.component.html, src/app/auth/components/registration/components/register/register.component.ts, src/app/auth/components/sign-in/sign-in.component.html, src/app/auth/components/sign-in/sign-in.component.ts, src/app/auth/routes/auth-routing.module.ts, src/app/aws-cognito/cognito/register.ts, src/app/core/constants/routes.ts, src/app/core/services/cce/authentication.service.ts, src/app/core/services/cce/dashboard.service.ts, src/app/models/cce/basic-registration.model.ts, src/app/pantry-locator/pantry-locator.component.ts, src/app/prompts/prompts/prompts.component.ts, src/environments/environment.ts
this is to clean up the login and signup pages
Has already been merged and checked in canary
=> Profile addorgselect

src/app/auth/components/registration/components/register/register.component.html, src/app/auth/components/registration/components/register/register.component.ts, src/app/information/information/information.component.html
this is to remove the org dropdown from register page
=> Register removeorg

package-lock.json, package.json, src/app/account/account.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/auth/routes/auth-routing.module.ts, src/app/core/constants/routes.ts, src/app/core/guards/auth.guard.ts, src/app/core/guards/logged-in-redirect.guard.spec.ts, src/app/core/guards/logged-in-redirect.guard.ts, src/app/core/models/auth-state.model.ts, src/app/core/services/cce/authentication.service.ts, src/app/dashboard/components/dashboard.component.ts, src/app/dashboard/routes/dashboard-routing.module.ts, src/app/information/information-routing.module.ts, src/app/prompts/prompts-routing.module.ts
- added auth guard
- removed user resolver (for now), tbd to use to load user and user profile
- updated routes to use auth guard and loggedin redirect guard
Updated routing behvavior
Not Logged In:
user will go to welcome page, can directly navigate to other unauthenicated pages as they could previously
Unspecified routes will all route back to / which will go to /welcome
Logged In:
If user goes back to /welcome or / , they will be routed to /dashboard
If user tried to goto an unspecified route (e.g., /archer), they will be taken to / which will be the dashboard
=> fix(routes): add auth guard, remove user-resolver, add on found route handling

src/app/auth/components/password-reset/password-reset.component.html, src/app/prompts/prompts/prompts.component.html, src/app/prompts/prompts/prompts.component.scss, src/app/prompts/prompts/prompts.component.ts
this is verified in QA and ready for Master
=> Updated styling

package-lock.json, package.json, src/app/account/account.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/auth/routes/auth-routing.module.ts, src/app/core/constants/routes.ts, src/app/core/guards/auth.guard.ts, src/app/core/guards/logged-in-redirect.guard.spec.ts, src/app/core/guards/logged-in-redirect.guard.ts, src/app/core/models/auth-state.model.ts, src/app/core/services/cce/authentication.service.ts, src/app/dashboard/components/dashboard.component.ts, src/app/dashboard/routes/dashboard-routing.module.ts, src/app/information/information-routing.module.ts, src/app/prompts/prompts-routing.module.ts
- added auth guard
- removed user resolver (for now), tbd to use to load user and user profile
- updated routes to use auth guard and loggedin redirect guard
- rebased with master
=> fix(routes): add auth guard, remove user-resolver usage

src/app/auth/components/password-forgot/password-forgot.component.html, src/app/auth/components/password-reset/password-reset.component.html, src/app/auth/components/validate-email/validate-email.component.html, src/app/auth/components/welcome-page/welcome.component.html, src/app/contact-us/contact-us.component.html, src/app/information/information/information.component.html, src/app/shared/site-header/site-header.component.html
- replaced relative ../../assets with assets
=> fix(assets): change path to be angular asset path

package-lock.json, package.json
Now when you attempt to commit changes, prettier auto format the staged files.
=> Add lint-staged and husky for automated prettier runs

src/app/dashboard/components/item-takepicture/item-takepicture.component.html, src/app/dashboard/components/item-takepicture/item-takepicture.component.ts
This leans on more native functionality per device, per https://gitlab.com/care-exchange/care-exchange-application/-/issues/110#note_363021614
=> Remove custom video canvas for takepicture
